### ISSUE TITLE
1.1.14 doesn't work w/ exrm

### ISSUE THREAD

**Issue by aaronjensen** [processone/fast_xml#10]
I end up seeing:

```
{"Kernel pid terminated",application_controller,"{application_start_failure,fast_xml,{bad_return,{{fast_xml,start,[normal,[]]},{'EXIT',{undef,[{p1_nif_utils,get_so_path,[fxml,[fast_xml],\"fxml\"],[]},{fxml,load_nif,0,[{file,\"/tmp/erlang/booking/edge/builds/booking/deps/fast_xml/src/fxml.erl\"},{line,43}]},{fast_xml,start,2,[{file,\"/tmp/erlang/booking/edge/builds/booking/deps/fast_xml/src/fast_xml.erl\"},{line,52}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,273}]}]}}}}}"}
```

when trying to boot the app.

**Comment by prefiks** [comment]
Hello,

That would suggest that there is missing dependency on p1_utils package, that is listed as such in both mix and rebar package. I'm not sure if exrm takes dependencies from one of those, or you need to specify that manually, but i am pretty sure if you make it include p1_utils package, you shouldn't be getting that error.

**Comment by aaronjensen** [comment]
Interesting. Here's a repro: https://github.com/aaronjensen/fast_xml_exrm_repro

cc @bitwalker

**Comment by andreabenini** [comment]
I have had the same problem reported from Aaron. It seems this issue could be resolved in two different modes:
- Include p1_utils package as a dependency, current rebar config is wrong
- Copy p1_nif_utils.erl (from p1_utils) in the src dir of this repository if you don't want a linked dependency. Just compile and it works.

First solution is better, the second is just an hack (even if it works)

**Comment by aaronjensen** [comment]
@andreabenini you might check out https://github.com/bitwalker/distillery

**Comment by cromain** [comment]
p1_utils was added long time ago. closing this old thread.
