### ISSUE TITLE
rebar3 fails to compile 

### ISSUE THREAD

**Issue by KunaPrime** [processone/fast_xml#15]
rebar3 seems to fail to compile fast_xml. Also it would be nice to say that is rebar is REQUIRED to build this.

**Comment by abunuwas** [comment]
Agree. Actually it shouldn't rely on rebar at all, rebar is deprecated. Makefile should be updated to use the new rebar3 API. 
You can compile manually with the following commands using rebar3:

```
rebar deps
rebar compile
```

**Comment by prefiks** [comment]
This was fixed some time ago.
