### ISSUE TITLE
multiple definition of `nif_init'

### ISSUE THREAD

**Issue by MonkSunBoy** [processone/fast_xml#18]
when I compile the fast_xml, I got this:

> 
c_src/fxml_stream.c:94: warning: ‘jabber_client_ns’ defined but not used
c_src/fxml_stream.c:115: warning: ‘dup_str’ defined but not used
c_src/fxml_stream.o: In function `nif_init':
/home/q/lffan.liu/qtalk-ejabber-tq/deps/fast_xml/c_src/fxml_stream.c:1061: multiple definition of `nif_init'
c_src/fxml.o:/home/q/lffan.liu/qtalk-ejabber-tq/deps/fast_xml/c_src/fxml.c:302: first defined here
collect2: ld returned 1 exit status
ERROR: cc c_src/fxml.o c_src/fxml_stream.o   -lexpat  -shared  -L/home/q/erlang1704/lib/erlang/lib/erl_interface-3.7.20/lib -lerl_interface -lei -o priv/fast_xml_drv.so failed with error: 1 and output:
c_src/fxml_stream.o: In function `nif_init':
/home/q/lffan.liu/qtalk-ejabber-tq/deps/fast_xml/c_src/fxml_stream.c:1061: multiple definition of `nif_init'
c_src/fxml.o:/home/q/lffan.liu/qtalk-ejabber-tq/deps/fast_xml/c_src/fxml.c:302: first defined here
collect2: ld returned 1 exit status

the version is:

> 
{fast_xml, ".*", {git, "https://github.com/processone/fast_xml", {tag, "1.1.18"}}},

**Comment by MonkSunBoy** [comment]
sorry, I got the answer. I lost the rebar.config file.

**Comment by yuvalfro** [comment]
Hi,
I have the same problem, could you explain the answer? what does it mean "I lost the rebar.config file"?
