### ISSUE TITLE
Makefile.mix:26: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.

### ISSUE THREAD

**Issue by johnhamelink** [processone/fast_xml#2]
Hi there,

I just tried to update to Ejabberd 16.2.0

When I recompiled the dependencies, I got the following:

```
==> fast_xml
Makefile.mix:26: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.
```

**Comment by mremond** [comment]
Indeed, good catch, thanks. It does not show up in my environment, but should be fixed now.

Can you please confirm this is ok for you ?

**Comment by johnhamelink** [comment]
Fixed for me now, thanks. For reference, I had to run `mix deps.update fast_xml` and then `mix deps.compile`.

Cheers! :rocket:
