### ISSUE TITLE
xmlrpc client library is missing

### ISSUE THREAD

**Issue by sngyai** [processone/fast_xml#23]
I'm sorry but I want to call a python xmlrpc server in ejabberd.
Before ejabberd 17, I used xmlrpc:call/4 in p1_xmlrpc[https://github.com/processone/p1_xmlrpc](url),
but after ejabberd refactor, p1_xmlrpc was removed, I don't know how to do that, please help me.
Thanks a lot.

**Comment by prefiks** [comment]
Sorry only server part of xmlrpc was left in ejabberd, probably just adding https://github.com/processone/p1_xmlrpc as dep and using that will still be possible.
