### ISSUE TITLE
How to question

### ISSUE THREAD

**Issue by nOmi7** [processone/fast_xml#26]
How can i create my own socket type and integrate to ejabberd on a seperate port?
for eg. socket type xml_stream goes to fast_xml what i wanted to create json_stream and get json records to erlang records how can easily use jiffy to use c2s but use json_stream instead of xml_stream ..
I understand this very non-standard use of ejabberd but i am expirementing on somethings for which I need an extra port to listing to json_streams.

**Comment by prefiks** [comment]
Probably easiest way to do that would be creating new listener and drive c2s module from that (like for example ejabberd_bosh does) with data that you get after your transformation of data that you receive from socket. There is no plugable mechanism for that in ejabberd so you would need to be a bit creative.
