### ISSUE TITLE
xmlcdata not parsed correctly with elixir

### ISSUE THREAD

**Issue by jonni-larjomaa** [processone/fast_xml#27]
Hi,

I have following xmlel

{:xmlel, "image", [{"width", "100"}, {"height", "100"}],
 [xmlcdata: "http://example.com/example.jpg"]}

and then i try to parse it with following code

el |> FastXML.xmlel |> :fxml.get_cdata

but only thing i get is empty string...

The whole sotry is that i get xmpp extended message stanza in following form

{:message, "", :normal, "", :undefined, :undefined, [], [], :undefined,
 [{:xmlel, "image", [{"width", "100"}, {"height", "100"}],
   [xmlcdata: "http://example.com/example.jpg"]}], %{}}

I can then run this through

stanza |> :xmpp.encode |> :fxml.get_subtag_cdata("image")

to get the cdata but in my opinion the whole thing should just work with

el |> :fxml.get_cdata

**Comment by zinid** [comment]
Not sure I can help you, I can barely understand Elixir code.

**Comment by zinid** [comment]
Great
