### ISSUE TITLE
BLOCKER - 1.1.34 is still broken due to p1_util 

### ISSUE THREAD

**Issue by motobob** [processone/fast_xml#37]
followup on #36 and i cannot re-open it. 
 
because the rebar.config.script unnecessarily changes direct git/tag/version deps to hex deps/version type of getting dependancies master branch still does not work .

Please fix it either in script file or just by publishing HEX.

@prefiks

**Comment by prefiks** [comment]
We will publish new hex release soon

**Comment by motobob** [comment]
this is fixed now. thanks
