### ISSUE TITLE
Elixir lib/* missing from hex.pm 

### ISSUE THREAD

**Issue by econnolly** [processone/fast_xml#4]
Hi. I've found that the **lib/fast_xml.ex** is not downloaded when I reference **fast_xml** from my **mix.exs** using:
```
defp deps do
  [{:fast_xml, "~> 1.1"}]
end
```
As a result, FastXML is not available (:fast_xml is, of course). I have had to reference github directly in order to get it to work:
```
defp deps do
  [{:fast_xml, github: "processone/fast_xml", tag: "1.1.8"}]
end
```

**Comment by mremond** [comment]
Thanks, good catch, it should be solved in 1.1.11.
