### ISSUE TITLE
Dependencies part

### ISSUE THREAD

**Issue by yuvalfro** [processone/fast_xml#40]
Hi,
I download the Expat XML parser from here: https://github.com/libexpat/libexpat/tree/R_2_2_9
I'm trying to use the configure options as you explained but I still get the "libexpat header file expat.h was not found".
I guess I'm just doing something wrong (probably the command line in the terminal or something), Is there a chance you can explain with more details what exactly I need to do (or write and where to write) in order for this to work?
Thanks

**Comment by prefiks** [comment]
On what os you are trying to compile this windows/linux/macos?

Usually setting CFLAGS="-I /path/to/expat/includes" and LDFLAGS="-L /path/to/expat/libs" should allow configure script to be able to locate required files.

**Comment by yuvalfro** [comment]
I'm using Ubuntu 20.04

**Comment by prefiks** [comment]
If you don't require your own expat build, then installing `libexpat1-dev` package will probably allow you to compile fast_xml without any special issues, as it will place required files in places that are searched by default.

**Comment by yuvalfro** [comment]
Great! libexpat1-dev works!
Thanks
