### ISSUE TITLE
multiple definition of `nif_init'

### ISSUE THREAD

**Issue by yuvalfro** [processone/fast_xml#41]
Hi,
I'm trying to run " ./configure && make" and I get this error:

==> fast_xml (compile)
/usr/bin/ld: c_src/fxml_stream.o: in function `nif_init':
/home/oem/fast_xml/fast_xml/c_src/fxml_stream.c:1060: multiple definition of `nif_init'; c_src/fxml.o:/home/oem/fast_xml/fast_xml/c_src/fxml.c:302: first defined here
collect2: error: ld returned 1 exit status
ERROR: sh(cc c_src/fxml.o c_src/fxml_stream.o $LDFLAGS -shared  -L"/usr/lib/erlang/lib/erl_interface-3.13.1/lib" -lerl_interface -lei -o priv/fast_xml_drv.so)
failed with return code 1 and the following output:
/usr/bin/ld: c_src/fxml_stream.o: in function `nif_init':
/home/oem/fast_xml/fast_xml/c_src/fxml_stream.c:1060: multiple definition of `nif_init'; c_src/fxml.o:/home/oem/fast_xml/fast_xml/c_src/fxml.c:302: first defined here
collect2: error: ld returned 1 exit status

ERROR: compile failed while processing /home/oem/fast_xml/fast_xml: rebar_abort

I saw that a few years ago someone had the same problem but he just said eventually "sorry, I got the answer. I lost the rebar.config file."
What does it mean to lose the rebar.config file? Is there a chance you can give more details about the solution?

Thanks!

**Comment by prefiks** [comment]
That seems strange, it looks like your build tries to compile both fxml_stream.c and fxml.c into single library, but in normal situation each of those files will be compiled and linked separately to two different .so files. Configuration in rebar.config should make rebar do that, maybe you indeed are for some reason missing rebar.config or rebar.config.script in directory where this lib is compiled?

**Comment by yuvalfro** [comment]
I have a folder called fast_xml (I cloned it from here), and inside it, I have another folder called rebar. The files rebar.config and rebar.config.script are in the rebar folder.
Maybe they should be in another location?

I upload a zip file of rebar.config and rebar.config.script if it helps somehow.
Thanks!

[rebar.zip](https://github.com/processone/fast_xml/files/5075204/rebar.zip)

**Comment by prefiks** [comment]
Those files should be in main directory just like they are in this repo, `git clone https://github.com/processone/fast_xml` + calling `rebar compile` of `make` in result of that should work.

**Comment by yuvalfro** [comment]
Yes, it worked thanks.
Now I have another problem (I'm sorry for all the questions, this is really the first time I'm trying to do something like this).
The "./configure && make" command ends like this:
==> p1_utils (get-deps)
==> fast_xml (get-deps)
==> p1_utils (compile)
==> fast_xml (compile)

After that when I try to do run the "application:start(fast_xml)" command I get this:
{error,{not_started,p1_utils}}

What is the problem now?
Thanks

**Comment by prefiks** [comment]
Try `application:ensure_all_started(fast_xml)`

**Comment by yuvalfro** [comment]
{error,{p1_utils,{"no such file or directory",
                  "p1_utils.app"}}}

This is weird, because inside the "fast_xml" directory I have "deps" directory, and inside it, I have "p1_utils" directory.

**Comment by prefiks** [comment]
How do you use that in your app? Usually if you for example would use rebar if you would specify fast_xml as your dependency, it should pull p1_utills and place it in same dir as fast_xml. If you doing that manually you need to replicate that (but i would suggest using rebar for handling deps).

**Comment by yuvalfro** [comment]
I'm not using it in my app yet.
I have a project in the university and the database of this project is 2.5GB XML file, someone in StackOverflow recommended me to use fast_xml, so right now I'm just trying to figure out how the fast_xml works and how it can help me.
I just learned in this course about erlang so I don't really have experience in using rebar.

**Comment by badlop** [comment]
I can reproduce that problem:

```shell
$ rebar -V
rebar 2.6.4 19 20161014_205218 No VCS info available.

$ cd fast_xml

$ erl -pa ebin/
Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1]

Eshell V11.0.2  (abort with ^G)
1> application:start(fast_xml).
{error,{not_started,p1_utils}}
2> application:ensure_all_started(fast_xml).
{error,{p1_utils,{"no such file or directory",
                  "p1_utils.app"}}}
^C
```

I found a dirty way to get it working:
```
$ erl -pa ebin/ -pa deps/p1_utils/ebin/
Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1]

Eshell V11.0.2  (abort with ^G)
1> application:start(fast_xml).             
{error,{not_started,p1_utils}}
2> application:ensure_all_started(fast_xml).
{ok,[p1_utils,fast_xml]}
3> application:start(fast_xml).             
{error,{already_started,fast_xml}}
4>  fxml_stream:parse_element(<<"<test>content cdata</test>">>).
{xmlel,<<"test">>,[],[{xmlcdata,<<"content cdata">>}]}
```

**Comment by yuvalfro** [comment]
Yes is work with "erl -pa ebin/ -pa deps/p1_utils/ebin/".
after this command "application:ensure_all_started(fast_xml)." it shows:
{ok,[crypto,p1_utils,fast_xml]}
You didn't have the word "crypto" in this line, does it matter?

And another thing, in here: <<"<test>content cdata</test>">>
i need to put the path to the XML file I want to parse?

**Comment by prefiks** [comment]
You can also call `rebar shell`, it should setup search path for you.

**Comment by badlop** [comment]
Hi @yuvalfro , can this issue be closed?

**Comment by yuvalfro** [comment]
> Hi @yuvalfro , can this issue be closed?

Yes, Thanks!
