### ISSUE TITLE
EUnit: 3 failing tests on Debian sid

### ISSUE THREAD

**Issue by debalance** [processone/fast_xml#48]
Hi, for a while now, fast_xml has 3 failing tests on Debian sid (they succeed on Debian stable).
It used to work when I packaged it last year, I could not find out what change has caused this.

As this doesn't seem to go away and is effectively blocking me from providing ejabberd for Debian testing (and thus Trixie),
I require your help as I have no clue how to track this down.

I am attaching the full build log for 1.1.51.
You can view the full build log for 1.1.49 at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1064722.
The issue is the same.
[erlang-p1-xml_1.1.51-1_amd64.build.txt](https://github.com/user-attachments/files/15612392/erlang-p1-xml_1.1.51-1_amd64.build.txt)

**Comment by prefiks** [comment]
This should be fixed by commit 054927a6788178ca276d88b5c8d8883f2b36fa25

**Comment by debalance** [comment]
That commit fixes the issue for me as well, thanks @prefiks !

@badlop I can simply download https://github.com/processone/fast_xml/commit/054927a6788178ca276d88b5c8d8883f2b36fa25.patch, place that in the Debian source package and the package builds again, so no need for a new release from my side, but thanks for the offer!
