### ISSUE TITLE
Fails to compile in Elixir 1.17 & OTP 27

### ISSUE THREAD

**Issue by jyc** [processone/fast_xml#49]
Hello!

Thanks for this excellent library.

I tried upgrading to Elixir/Mix 1.17 and ran into this error while using `fast_xml` 1.1.51:

```
$ mix deps.compile fast_xml
...
===> Setting paths to [deps]
===> Compile (apps)
===> Setting paths to [plugins]
===> Setting paths to [deps]
===> Setting paths to [plugins]
===> Setting paths to [plugins]
===> Expanded command sequence to be run: []
===> Running provider: do
===> Expanded command sequence to be run: [app_discovery,{bare,compile}]
===> Running provider: app_discovery
===> Found top-level apps: [fast_xml]
	using config: [{src_dirs,["src"]},{lib_dirs,["apps/*","lib/*","."]}]
===> Setting paths to [deps]
===> Compile (apps)
===> Setting paths to [plugins]
===> Setting paths to [deps]
===> Setting paths to [plugins]
===> Setting paths to [plugins]
===> Not adding provider pc compile from module pc_prv_compile because it already exists from module pc_prv_compile
===> Not adding provider pc clean from module pc_prv_clean because it already exists from module pc_prv_clean
===> Running provider: {bare,compile}
===> Compile (untagged)
===> Running hooks for compile in app fast_xml (/Users/jyc/projects/foo/server/deps/fast_xml) with configuration:
===> Setting paths to [plugins]
===> 	{provider_hooks, [{pre, [{pc,compile}]}]}.
===> Running provider: {pc,compile}
===> Running hooks for {pc,compile} with configuration:
===> 	{provider_hooks, []}.
===> 	{pre_hooks, []}.
===> run_hooks("/Users/jyc/projects/foo/server/deps/fast_xml", pre_hooks, {pc,
                                                                             compile}) -> no hooks defined

===> Uncaught error in rebar_core. Run with DIAGNOSTIC=1 to see stacktrace or consult rebar3.crashdump
===> Uncaught error: undef
===> Stack trace to the error location:
[{pc_port_env,construct,
     [{state_t,"/Users/jyc/projects/foo/server/deps/fast_xml",
          {dict,21,16,16,8,80,48,
              {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
              {{[],
...
** (Mix) Could not compile dependency :fast_xml, "/Users/jyc/.asdf/installs/elixir/1.17.0-otp-27/.mix/elixir/1-17/rebar3 bare compile --paths /Users/jyc/projects/arity/server/_build/dev/lib/*/ebin" command failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile fast_xml --force", update it with "mix deps.update fast_xml" or clean it with "mix deps.clean fast_xml"
```

The full error message is here: [error.txt](https://github.com/user-attachments/files/15812244/error.txt)

At a first glance it looks like maybe the `pc` plugin is incompatible with the OTP 27. I ran across another issue in a processone project but it seems unrelated: https://github.com/processone/ejabberd/issues/4186

**Comment by jyc** [comment]
I tried a fresh install and noticed it mentioned pc v1.14.0—the other issue mentioned upgrading to 1.15.0 for OTP 27, so I'll see if that helps

```
$ mix deps.clean --all
$ mix deps.compile fast_xml
===> Fetching pc v1.14.0
===> Analyzing applications...
===> Compiling pc
===> Compiling _build/default/plugins/pc/src/pc_port_env.erl failed
_build/default/plugins/pc/src/pc_port_env.erl:190:10: code:lib_dir/2 is deprecated; this functionality will be removed in a future release

===> Errors loading plugin pc. Run rebar3 with DEBUG=1 set to see errors.
===> Analyzing applications...
===> Compiling pc
===> Uncaught error in rebar_core. Run with DIAGNOSTIC=1 to see stacktrace or consult rebar3.crashdump
===> When submitting a bug report, please include the output of `rebar3 report "your command"`
** (Mix) Could not compile dependency :fast_xml, "/Users/jyc/.asdf/installs/elixir/1.17.0-otp-27/.mix/elixir/1-17/rebar3 bare compile --paths /Users/jyc/projects/arity/server/_build/dev/lib/*/ebin" command failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile fast_xml --force", update it with "mix deps.update fast_xml" or clean it with "mix deps.clean fast_xml"
```

**Comment by jyc** [comment]
Forcing rebar to install pc 1.15.0 did not help. It is also odd because looking at the line that errors:

```
# in pc_port_specs.erl
port_opt(State, {env, Env}) ->
    {ok, PortEnv} = pc_port_env:construct(State, Env),
    {env, PortEnv};
```

I do see `pc_port_env:construct/2` defined in `pc_port_env.erl` on my machine, so I'm not sure why I'm getting `undef`.

**Comment by prefiks** [comment]
Yes this is likely issue with pc and erlang 27. Could you see if executing `rebar3 plugin upgrade` helps with that? If you get error about not having rebar3, could you do `mix local.rebar` and use path from that for rebar3?

**Comment by badlop** [comment]
It seems you don't compile the library directly, you have it defined as a dependency in a mix application, right? Maybe you have other dependency that requires pc 1.14, and fast_xml is forced to use that old version too.

As a counter-example, let's see ejabberd: in its mix.exs it defines fast_xml and many other dependencies. Many of those dependencies require pc too, but none of them requires any specific pc version, so rebar3 downloads the latest one: pc 1.15:

<details>

``` bash
$ erl -version
Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 15.0
$ cd ejabberd/
$ mix deps.get fast_xml
...
$ mix  deps.compile fast_xml
===> Fetching pc v1.15.0
===> Analyzing applications...
===> Compiling pc
===> Compiling c_src/fxml.c
===> Compiling c_src/fxml_stream.c
===> Linking /home/bernar/e/git/ejabberd/_build/dev/lib/fast_xml/priv/lib/fxml.so
===> Linking /home/bernar/e/git/ejabberd/_build/dev/lib/fast_xml/priv/lib/fxml_stream.so
===> Analyzing applications...
===> Compiling fast_xml
$ 
```
</details>

Compiling fast_xml with OTP 27 works great in the [fast_xml CI](https://github.com/processone/fast_xml/actions/runs/9399587506/job/26176240782), in [ejabberd's CI](https://github.com/processone/ejabberd/actions/runs/9452544391/job/26035982402) and [Runtime](https://github.com/processone/ejabberd/actions/runs/9491090305).

**Comment by jyc** [comment]
> Yes this is likely issue with pc and erlang 27. Could you see if executing `rebar3 plugin upgrade` helps with that? If you get error about not having rebar3, could you do `mix local.rebar` and use path from that for rebar3?

@prefiks I ran the command you suggested after the commands from my last comment and it worked! Thank you!

```
$ rebar3 plugins upgrade --all 
===> Upgrading pc v1.15.0
===> Analyzing applications...
===> Compiling pc
$ make                        
rebar get-deps
===> Verifying dependencies...
rebar compile
===> Verifying dependencies...
===> Compiling c_src/fxml.c
===> Compiling c_src/fxml_stream.c
===> Linking /Users/jyc/projects/fast_xml/priv/lib/fxml.so
===> Linking /Users/jyc/projects/fast_xml/priv/lib/fxml_stream.so
===> Analyzing applications...
===> Compiling fast_xml
```

**Comment by jyc** [comment]
Ah, I see now that I have to run `rebar plugins list` in order for the change to `rebar.config.script` to take effect. So it looks like upgrading to 1.15.0 just like in https://github.com/processone/ejabberd/issues/4186 fixes it; I just failed to actually apply it.

**Comment by badlop** [comment]
> rebar compile

Please notice that `make` uses `rebar`, not `rebar3`.

**Comment by jyc** [comment]
> Please notice that make uses rebar, not rebar3.

rebar is just a symlink to rebar3 on my computer.

**Comment by jyc** [comment]
It looks like what happened is that I had previously compiled `fast_xml` when the latest version of `pc` was still 1.14.0. I checked the Rebar3 [docs](https://rebar3.org/docs/configuration/plugins/#upgrading-plugins) and they say:

> Plugins work a bit like dependencies (although they are currently not being version-locked); they will not be automatically updated unless you ask for them to be.
> ...
> If you are using Hex packages as plugins and you do not see the version you expected, remember to use call rebar3 update to get a fresh Hex index. Once again, since plugins are not locked as part of the lock file, it might be a good idea to always specify a version for them.

I think that's why @prefiks's suggestion to run `rebar3 plugins upgrade --all` worked. That also explains why compiling `fast_xml` works in CI.

Separately, in a Mix project using `fast_xml`, I had to just `rm -rf deps`. (It looks like Mix compiles each dependency in its own directory, with its own set of Rebar3 plugins, e.g. `deps/fast_xml/_build/default/plugins/pc`, so I don't think the version of `pc` used by another dependency can actually interfere).

Thanks all for the help! Would you accept a small PR that just contains this patch? I'd be happy to make one if so!

```diff
diff --git a/rebar.config.script b/rebar.config.script
index 3e6073b..ccdd4a3 100644
--- a/rebar.config.script
+++ b/rebar.config.script
@@ -134,7 +134,7 @@ Rules = [
         {[deps], IsRebar3,
          Rebar3DepsFilter, []},
         {[plugins], IsRebar3,
-         AppendList([pc]), []},
+         AppendList([{pc, "1.15.0"}]), []},
         {[provider_hooks], IsRebar3,
          AppendList([{pre, [
                             {compile, {pc, compile}},
```

**Comment by badlop** [comment]
Great, thanks for all the details!

I've added such a requirement to this library and the other ones that include C code.

By setting `{pc, "~> 1.15.0"}`, it will also accept bugfix releases like "1.15.1", "1.15.2" in  case they are released.
