### ISSUE TITLE
How much is this repo faster than processone/xml

### ISSUE THREAD

**Issue by everimbaq** [processone/fast_xml#8]

**Comment by everimbaq** [comment]
I'm using  oldest version of the repo processone/xml ,which maybe 1.1.0 or earlier, do I need to change to
fast_xml? How much is this repo faster than processone/xml? 
Thanks

**Comment by prefiks** [comment]
That rename was mostly done to stop using xml module name that conflicted with some other package, there was couple changes that did improve performance since 1.1.0, but you maybe can expect couple percent improvement.
